### ISSUE TITLE
Validate stage order in API calls once validation functions are confirmed.

### ISSUE THREAD

**Issue by bharathcs** [sivayogasubramanian/caza#41]
Blocked by #36 

Checks required at:

- [x] POST stages
- [x] PATCH stages/:stageID
- [x] DELETE stages/:stageId

After this, only direct prisma / Postgres action should be able to cause stage orders to go bad.

**Comment by sivayogasubramanian** [comment]
@bharathcs what is the status of this?

**Comment by bharathcs** [comment]
Fixed by @zognin in #65
